name: Python application test with Pytest

on:
  pull_request:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GCP_CREDENTIALS: ${{ secrets.GAP_DEV_AUTH }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Create GCP Credentials
      run: echo "$GCP_CREDENTIALS" > gcp_credentials.json

    - name: Test with pytest
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS=gcp_credentials.json
        pytest -vv

    - name: Show pytest failure in PR if it occurs
      uses: actions/github-script@v3
      if: ${{ failure() }}
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const issue_number = context.issue.number;
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Testes falharam! Cheque a página do Actions para mais detalhes.'
          });
